#!/bin/bash

START="no"

if [ "$XIM_PROGRAM" = "uim-xim" ]; then
  START="yes"
fi

if [ "$GTK_IM_MODULE" = "uim" ]; then
  START="yes"
fi

if [ "$QT_IM_MODULE" = "uim" ]; then
  START="yes"
fi

if [ "$START" = "yes" ]; then
  uim-xim &

  if [ -n "$1" ]; then
    if which "uim-toolbar-$1" > /dev/null 2>&1; then
      "uim-toolbar-$1"
    fi
  fi
fi
